### ISSUE TITLE
Error: process.mixin() has been removed. 

### ISSUE THREAD

**Issue by ptarjan** [technoweenie/twitter-node#1]
Running your example code with the newest version of node.js gives

```
node user_server.js
Error: process.mixin() has been removed.
    at EventEmitter.mixin (node.js:11:11)
    at EventEmitter.stream (/var/www/paul.slowgeek.com/twitter2facebook/twitter-node/lib/index.js:92:24)
    at Object.<anonymous> (/var/www/paul.slowgeek.com/twitter2facebook/user_server.js:47:4)
    at Module._compile (module:385:23)
    at module:413:20
    at fs:52:23
    at node.js:164:9
```

**Comment by technoweenie** [comment]
What's a good replacement for process.mixin?  That's a recent node.js removal.

**Comment by ptarjan** [comment]
No idea, you code is my first foray into node.js.

**Comment by technoweenie** [comment]
If you check out v0.1.90 of node and compile it, it should work with TwitterNode until I can get a replacement for `process.mixin()`

http://github.com/ry/node/tree/v0.1.90

**Comment by tim-smart** [comment]
`process.mixin` has been removed recently.
