### ISSUE TITLE
Error: Cannot find module 'twitter-node'

### ISSUE THREAD

**Issue by cocodrino** [technoweenie/twitter-node#11]
Hi...I've tried install your module using npm and downloading the git and creating the symbolic link too but always get this error 

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: Cannot find module 'twitter-node'
    at Function._resolveFilename (module.js:320:11)
    at Function._load (module.js:266:25)
    at require (module.js:348:19)
    at Object.<anonymous> (/home/yo/Descargas/libros/rm_proj/sinatra_auth/public/twino.js:2:19)
    at Module._compile (module.js:404:26)
    at Object..js (module.js:410:10)
    at Module.load (module.js:336:31)
    at Function._load (module.js:297:12)
    at Array.<anonymous> (module.js:423:10)

i don't get any error or warning  when I install this using npm...but this don't work...it's really weird :s

**Comment by Pet3ris** [comment]
Seconded. I've tried all the methods in this article http://stackoverflow.com/questions/5047542/node-js-cannot-find-module-xml2js to no avail.
