### ISSUE TITLE
TypeError: Object #<Object> has no method 'createClient' after npm update

### ISSUE THREAD

**Issue by itwars** [technoweenie/twitter-node#18]
First due to the ssl change I've tried to update twitter-node using _npm update_ but nothing have been updated because the version is always 0.0.2 ... I copied index.js manualy !

But after that, I got this error :

``` javascript
node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
TypeError: Object #<Object> has no method 'createClient'
    at EventEmitter._createClient (/home/vrabah/node_modules/twitter-node/lib/twitter-node/index.js:160:15)
    at EventEmitter.stream (/home/vrabah/node_modules/twitter-node/lib/twitter-node/index.js:111:22)
    at Object.<anonymous> (/home/vrabah/Documents/projet/node.js/mydev/server3.js:34:2)
    at Module._compile (module.js:411:26)
    at Object..js (module.js:417:10)
    at Module.load (module.js:343:31)
    at Function._load (module.js:302:12)
    at Array.<anonymous> (module.js:430:10)
    at EventEmitter._tickCallback (node.js:126:26)

```

Any idea ?
Thank's

**Comment by rickymuvel** [comment]
the correct code:
var mysql      = require('mysql');
var connection = mysql.createConnection({
  host     : 'localhost',
  user     : 'me',
  password : 'secret',
});

connection.connect();

connection.query('SELECT 1', function(err, rows, fields) {
  if (err) throw err;

  console.log('Query result: ', rows);
});

connection.end();

https://github.com/felixge/node-mysql

**Comment by crifan** [comment]
actually, another place give detailed explanaton why change to this kind of code:
https://github.com/nearinfinity/node-persist/issues/45

**Comment by mithunbillara** [comment]
NodeJS and npm installation for win7
1.)install node.js(http://nodejs.org/ )
2.)create new folder(ex:c:/wamp/www/mynode)

run command

3.)npm install express 

4.)npm install socket.io 

5.)npm install mysql@2.0.0-alpha8

refference

http://spiritconsulting.com.ar/fedex/2010/11/how-to-install-nodejs-express-socket- 
https://npmjs.org/package/socket.io
