### ISSUE TITLE
calling twit.stream(); from within a function gives a connection refusal

### ISSUE THREAD

**Issue by anthonywebb** [technoweenie/twitter-node#24]
If I call twit.stream(); from within a function (any function) I get a connection refused error:

node.js:134
        throw e; // process.nextTick error, or 'error' event on first tick
        ^
Error: ECONNREFUSED, Connection refused
    at Client._onConnect (net.js:595:18)
    at IOWatcher.onWritable [as callback](net.js:186:12)

Can anyone guess why this would be?

**Comment by anthonywebb** [comment]
Problem is that the stuff in NPM is out of date.  Will the latest ever be able to be pulled form NPM or has this project been abandoned?

**Comment by phillyqueso** [comment]
Seconded!
